[package]
name = "bed"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
clap = { version = "4.5.16", features = ["derive"] }
futures = "0.3.30"
serde = { version = "1.0.208", features = ["derive"] }
serde_yml = "0.0.11"
tokio = { version = "1.39.2", features = ["full"] }
